### ISSUE TITLE
学习进度 has_read_by_user?(user) 报错

### ISSUE THREAD

**Issue by destinyd** [mindpin/kc_courses#19]
``` shell
2.2.0 :021 > ware.has_read_by_user? user
NoMethodError: undefined method `read_percent' for nil:NilClass
    from /Users/DD/.rvm/gems/ruby-2.2.0@mindpin/bundler/gems/kc_courses-8f6d9c3e2449/app/models/kc_courses/concerns/ware_reading_method.rb:29:in `has_read_by_user?'
    from (irb):21
    from /Users/DD/.rvm/gems/ruby-2.2.0@mindpin/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
    from /Users/DD/.rvm/gems/ruby-2.2.0@mindpin/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
    from /Users/DD/.rvm/gems/ruby-2.2.0@mindpin/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /Users/DD/.rvm/gems/ruby-2.2.0@mindpin/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Users/DD/.rvm/gems/ruby-2.2.0@mindpin/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

**Comment by destinyd** [comment]
其余方法也有此问题

``` ruby
ware_readings.where(creator: user)
```

这种形式不行的，

要用

``` ruby
ware_readings.where(creator_id: user.id.to_s)
```
